spring:
  application:
    name: ai-exchange
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/ai_exchange?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    async:
      request-timeout: 600000  # 异步请求超时时间10分钟（毫秒）
server:
  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 600000  # Tomcat连接超时10分钟（毫秒）
    keep-alive-timeout: 600000  # keep-alive超时10分钟（毫秒）

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max


alphavantage:
  api:
